[at2222][pv622] Update .gitlab-ci.yml - add scala-cli installation

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,15 @@
+before_script:
+  - |
+    if ! command -v scala-cli &> /dev/null
+    then
+      echo "Installing scala-cli..."
+      curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
+      chmod +x cs
+      ./cs install scala-cli
+    else
+      echo "scala-cli is already installed."
+    fi
+
 stages:
   - build
   - test
@@ -13,8 +25,7 @@ test_job:
   script:
     - scala-cli test . > test_output.txt || true
     - FAILED_TESTS=$(grep -c "FAILED" test_output.txt)
-    - echo "Number of tests failed"
-    - echo $FAILED_TESTS
+    - echo "Number of tests failed: $FAILED_TESTS"
   artifacts:
     paths:
       - test_output.txt
